# Generated by Django 3.2.16 on 2023-01-04 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='등록시간')),
                ('title', models.TextField(max_length=128, verbose_name='리뷰제목')),
                ('contents', models.TextField(verbose_name='리뷰내용')),
                ('hits', models.PositiveBigIntegerField(default=0, verbose_name='조회수')),
                ('top_fixed', models.BooleanField(default=False, verbose_name='상단고정')),
                ('review_image', models.ImageField(blank=True, upload_to='rImg', verbose_name='리뷰이미지')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.place', verbose_name='장소')),
            ],
        ),
    ]
