# Generated by Django 3.2.16 on 2023-01-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_file', models.FileField(blank=True, unique=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='장소 이름')),
                ('place_address', models.TextField(blank=True, verbose_name='장소 주소')),
                ('place_latitude', models.FloatField(verbose_name='위도')),
                ('place_longitude', models.FloatField(verbose_name='경도')),
                ('place_phone', models.TextField(blank=True, verbose_name='전화번호')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(blank=True, max_length=128, verbose_name='입력 텍스트')),
                ('result', models.TextField(blank=True, verbose_name='출력 장소')),
            ],
        ),
    ]
